name: Test rerun failed jobs

on:
    push:
        branches:
            - "main"
        
permissions:
  actions: write
  contents: write

jobs:
    some-other-step:
        runs-on: ubuntu-latest
        steps:
            - name: This step always fails
              run: sleep 10 && exit 1

    retry-on-failure:
        if: failure() && fromJSON(github.run_attempt) < 4
        needs: [some-other-step]
        runs-on: ubuntu-latest
        steps:
            - env:
                  GH_REPO: ${{ github.repository }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: | 
                echo ${{github.run_attempt}}
                gh workflow run rerun-workflow.yml -F run_id=${{ github.run_id }}